### ISSUE TITLE
Please update deprecated fields / Military.com

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-militarydotcom#20]
As follows:

mortgage.application.credit_rating --> credit_rating
mortgage.application.bankruptcy --> 
mortgage.bankruptcy.was_discharged

**Comment by zalary** [comment]
I've tried everything I know to make these autoclose, but alas, they don't.

**Comment by kcaponeAP** [comment]
We are still seeing issues with credit rating not passing. 

https://next.leadconduit.com/events/54e7ceee9bce51171bd38650?event_id=54e7ceef9bce51171bd38655

This is for the client CW

**Comment by kcaponeAP** [comment]
Closing. Stale lead.

**Comment by kcaponeAP** [comment]
@alexj there are still 2 deprecated fields listed on the Military integration. Can these be updated?

http://docs.leadconduit.com/fields?q=military.com%20inbound

Application Credit Rating & 
Application Bankruptcy

![screen shot 2015-08-03 at 5 47 48 pm](https://cloud.githubusercontent.com/assets/8238417/9049456/c874dfec-3a07-11e5-9aa7-03d72b5bae08.png)

**Comment by zalary** [comment]
Several inbound setups are still using the deprecated fields in the MLOA flow.  For example:

<img width="1052" alt="screen shot 2015-08-03 at 5 53 25 pm" src="https://cloud.githubusercontent.com/assets/338654/9049540/b4991398-3a08-11e5-989b-fdc58f827783.png">

and this is simply one mapping for one inbound source for one flow.

before we removed these fields, we need to make sure that there are no instances of them being used in any inbound integrations and/or in any mappings.

cc @alexj @alexkwolfe @kcaponeAP

**Comment by zalary** [comment]
Resolved by Version 0.2.3
