### ISSUE TITLE
Please add support for First_Mortgage_Balance

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-militarydotcom#22]
We are not seeing the Costco integration successfully acknowledge &First_Mortgage_Balance=100000 in the inbound POST data. 

Client is CW:

https://next.leadconduit.com/events/54ebba6ac191d6452e1bcf1c

**Comment by alexkwolfe** [comment]
Pretty sure this is a problem with the Costco integration, so I went ahead and opened an issue there instead.

https://github.com/activeprospect/leadconduit-integration-costco/issues/20
