### ISSUE TITLE
Question on BEST_TIME_TO_CALL

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-militarydotcom#23]
A recent lead came in with BEST_TIME_TO_CALL - yet LCN it did not accept the value of 'Morning'

https://next.leadconduit.com/events/5594384261dac6a90b5de3d6?source_id=53fba074b60c389f17ca4d7c&type=source

Can someone please inspect why this happened?

**Comment by kcaponeAP** [comment]
I'm also having the same issue with the following: 

GROSS_ANNUAL_INCOME=97500
CREDIT_RATING=Good

**Comment by kcaponeAP** [comment]
closing.. i see the values should be 1 or 2.

**Comment by zalary** [comment]
We are expecting 

BEST_TIME_TO_CALL 
1 =  'morning'
2 = 'afternoon'
3 = 'evening'

CREDIT_RATING is similar - expecting a 1 - 4 value

GROSS_ANNUAL_INCOME is calculated into Monthly Salary
